# Generated by Django 4.0.4 on 2024-07-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_station', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['cargo', 'seat']},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('journey', 'cargo', 'seat')},
        ),
    ]
