# Generated by Django 4.0.4 on 2024-07-19 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_station', '0003_alter_ticket_options_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='train_station.journey'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='train_station.order'),
        ),
    ]
