# Generated by Django 4.0.4 on 2024-07-22 15:38

from django.db import migrations, models
import train_station.models


class Migration(migrations.Migration):

    dependencies = [
        ('train_station', '0005_alter_journey_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='image',
            field=models.ImageField(null=True, upload_to=train_station.models.station_image_file_path),
        ),
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(null=True, upload_to=train_station.models.train_image_file_path),
        ),
    ]
